Send application events before/after RabbitMQ consumer subscribe to a queue
micronaut-projects/micronaut-rabbitmq pull request #515
Opened 2023-08-03 14:21 UTC by guillermocalvo

Closes #423 

Instead of delaying message consumption, we will emit application events so that users can take any necessary actions before/after RabbitMQ consumers subscribe to a queue.

2023-08-04 07:04 UTC, sdelamo requested changes

2023-08-04 07:04 UTC, sdelamo commented on docs-examples/example-groovy/src/test/groovy/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.groovy
> +    System.out.println("RabbitMQ consumer: ${event.source} (method: ${event.method}) is subscribing to: ${event.queue}")
use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

2023-08-04 07:04 UTC, sdelamo commented on docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.java
> +    System.out.println(new StringBuilder()
use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

2023-08-04 07:04 UTC, sdelamo commented on docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.java
> +    System.out.println(new StringBuilder()
use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

2023-08-04 07:04 UTC, sdelamo commented on docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.kt
> +    println("RabbitMQ consumer: ${event.source} (method: ${event.method}) just subscribed to: ${event.queue}")
use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

2023-08-04 07:04 UTC, sdelamo commented on docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.kt
> +    println("RabbitMQ consumer: ${event.source} (method: ${event.method}) is subscribing to: ${event.queue}")
use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

2023-08-04 07:04 UTC, sdelamo commented
@aniljaiswal Will this proposed solution help your use case?

2023-08-04 09:45 UTC, sdelamo requested changes

2023-08-04 09:45 UTC, sdelamo commented on rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
>      public RabbitMQConsumerAdvice(BeanContext beanContext,
annotate the new constructor with `@Inject`

2023-08-05 08:15 UTC, sdelamo requested changes

2023-08-05 08:15 UTC, sdelamo commented on rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
> +     * @deprecated
tell users in the `@deprecated` java doc to use the other constructor instead with `{@link`

2023-08-07 07:42 UTC, guillermocalvo commented on rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
> +     * @deprecated
```suggestion
     * @deprecated Use @{link {@link RabbitMQConsumerAdvice#RabbitMQConsumerAdvice(BeanContext, ApplicationEventPublisher, ApplicationEventPublisher, RabbitBinderRegistry, RabbitListenerExceptionHandler, RabbitMessageSerDesRegistry, ConversionService, List)}}
```

2023-08-14 11:39 UTC, sdelamo requested changes

2023-08-14 11:39 UTC, sdelamo commented on rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
> +            beanContext.findBean(Argument.of((Class<ApplicationEventPublisher<RabbitConsumerStarting>>) ((Class) ApplicationEventPublisher.class),
```suggestion
            beanContext.getBean(Argument.of(ApplicationEventPublisher.class, RabbitConsumerStarting.class)),
```

2023-08-14 11:39 UTC, sdelamo commented on rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
> +                Argument.of(RabbitConsumerStarting.class))).orElseThrow(),
```suggestion
```

2023-08-14 11:39 UTC, sdelamo commented on rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
> +            beanContext.findBean(Argument.of((Class<ApplicationEventPublisher<RabbitConsumerStarted>>) ((Class) ApplicationEventPublisher.class),
```suggestion
            beanContext.getBean(Argument.of(ApplicationEventPublisher.class, RabbitConsumerStarted.class)),
```

2023-08-14 11:39 UTC, sdelamo commented on rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
> +                Argument.of(RabbitConsumerStarted.class))).orElseThrow(),
```suggestion
```

2023-08-14 15:05 UTC, merged